services:
  soju:
    restart: unless-stopped
    container_name: soju
    image: ghcr.io/glennbrown/soju:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.config/soju:/var/lib/soju:Z
      - ~/.local/share/soju/logs:/var/lib/soju/logs:Z
      - ~/.local/share/soju/uploads:/home/soju/uploads:Z
      - /etc/letsencrypt/live/mydomain.com/fullchain.pem:/etc/ssl/certs/soju/soju.crt
      - /etc/letsencrypt/live/mydomain.com/privkey.pem:/etc/ssl/certs/soju/soju.key
    ports:
     - 46697:6697